#!/usr/bin/env node
// Emits CSS custom properties from the app's design tokens.
// Usage: node tools/tokens-to-css.mjs $APP/designtoken/tokens.json > assets/tokens.css
import { readFileSync } from 'node:fs';
const t = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const lines = [];
const walk = (obj, prefix) => {
  for (const [k, v] of Object.entries(obj)) {
    const name = `${prefix}-${k}`.replace(/[^a-zA-Z0-9-]/g, '-');
    if (v && typeof v === 'object' && !Array.isArray(v)) { walk(v, name); continue; }
    const unit = typeof v !== 'number' ? '' : /duration/i.test(name) ? 'ms' : 'px';
    lines.push(`  --${name}: ${v}${unit};`);
  }
};
walk(t.colors.light, 'c');
walk(t.radius, 'r');
walk(t.spacing, 's');
walk(t.motion, 'm');
process.stdout.write(`/* generated by tools/tokens-to-css.mjs from the app's designtoken/tokens.json — do not edit by hand */\n:root {\n${lines.join('\n')}\n}\n`);
